# Generated by Django 3.2.19 on 2023-10-04 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ageGroupModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageRange', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ageGroup_table',
            },
        ),
        migrations.CreateModel(
            name='performanceModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('artistId', models.ForeignKey(default=True, max_length=250, on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='User_App.useraccountmodels')),
            ],
            options={
                'db_table': 'Performance_table',
            },
        ),
        migrations.CreateModel(
            name='injuryRecordModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('injuryDescription', models.CharField(max_length=500)),
                ('artistId', models.ForeignKey(default=True, max_length=250, on_delete=django.db.models.deletion.CASCADE, related_name='injuryRecord', to='User_App.useraccountmodels')),
            ],
            options={
                'db_table': 'injuryRecord_table',
            },
        ),
        migrations.CreateModel(
            name='clubActivitiesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('artistId', models.ForeignKey(default=True, max_length=250, on_delete=django.db.models.deletion.CASCADE, related_name='clubActivities', to='User_App.useraccountmodels')),
            ],
            options={
                'db_table': 'clubActivities_table',
            },
        ),
        migrations.CreateModel(
            name='attendanceRecordModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('artistId', models.ForeignKey(default=True, max_length=250, on_delete=django.db.models.deletion.CASCADE, related_name='attendanceRecord', to='User_App.useraccountmodels')),
            ],
            options={
                'db_table': 'attendanceRecord_table',
            },
        ),
    ]
